import type { Metadata } from 'next'
import LegalPage, { type LegalSection } from '@/components/LegalPage'

export const metadata: Metadata = {
  title: 'Terms of Service | CatScanner',
  description: 'The terms that govern your use of CatScanner.org.',
  alternates: { canonical: 'https://catscanner.org/terms' },
}

const sections: LegalSection[] = [
  {
    h: 'The Service',
    p: [
      'CatScanner provides AI-assisted cat breed identification and related content. Results are estimates generated by artificial intelligence and are provided for informational purposes only.',
    ],
  },
  {
    h: 'Eligibility and Accounts',
    ul: [
      'You must be at least 13 years old (or the age of digital consent in your country) to use CatScanner.',
      'You are responsible for the accuracy of your account information and for keeping your password secure.',
      'You are responsible for all activity that happens under your account.',
    ],
  },
  {
    h: 'Credits, Plans, and Free Tier',
    p: [
      'Some features use credits or require a paid plan. New users receive free credits. Free and paid allowances, and what they include, are described on our Pricing page and may change over time.',
    ],
  },
  {
    h: 'Billing and Payments',
    p: [
      'Purchases and subscriptions are sold and processed by Paddle.com Market Ltd, our Merchant of Record. By purchasing, you also agree to Paddle’s buyer terms.',
      'Subscriptions renew automatically at the end of each billing period unless cancelled beforehand. Prices may include applicable taxes, and we may change prices with notice.',
    ],
  },
  {
    h: 'Free Trials',
    p: [
      'Where a free trial is offered on a paid plan, you will be charged when the trial ends unless you cancel before then. You can cancel anytime from your account.',
    ],
  },
  {
    h: 'Refunds and Cancellation',
    p: [
      'You can cancel your subscription at any time. Refunds are handled according to our Refund Policy, which forms part of these Terms.',
    ],
  },
  {
    h: 'Acceptable Use',
    p: ['When using CatScanner you agree not to:'],
    ul: [
      'Break any law or infringe anyone’s rights.',
      'Upload content you do not have the right to use.',
      'Attempt to disrupt, reverse-engineer, scrape, or overload the service.',
      'Resell or misuse the service or your account.',
    ],
  },
  {
    h: 'Intellectual Property',
    p: [
      'CatScanner, its software, content, and branding are owned by us or our licensors. You retain ownership of the photos you upload, and you grant us a limited license to process them solely to provide the service.',
    ],
  },
  {
    h: 'AI Results — No Veterinary Advice',
    p: [
      'Breed identifications and care information are AI-generated estimates and may be inaccurate. They are not a substitute for professional veterinary advice. Always consult a qualified veterinarian for the health and care of your cat.',
    ],
  },
  {
    h: 'Disclaimers and Limitation of Liability',
    p: [
      'The service is provided “as is” without warranties of any kind. To the fullest extent permitted by law, CatScanner is not liable for any indirect, incidental, or consequential damages arising from your use of the service.',
    ],
  },
  {
    h: 'Termination',
    p: [
      'We may suspend or terminate accounts that violate these Terms. You may stop using CatScanner and delete your account at any time.',
    ],
  },
  {
    h: 'Changes to These Terms',
    p: [
      'We may update these Terms from time to time. Continued use after changes means you accept the updated Terms.',
    ],
  },
  {
    h: 'Governing Law',
    p: [
      'These Terms are governed by the applicable law of our place of operation, without regard to conflict-of-law rules.',
    ],
  },
]

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="June 14, 2026"
      intro="These Terms of Service (“Terms”) govern your use of CatScanner.org. By accessing or using CatScanner you agree to these Terms. If you do not agree, please do not use the service."
      sections={sections}
    />
  )
}
